#!/bin/bash


if [ $1 = "start" ]
then
sudo /opt/lampp/lampp startapache
elif [ $1 = "stop" ]
then
sudo /opt/lampp/lampp stop
elif [ $1 = "panel" ]
then
sudo /opt/lampp/manager-linux-x64.run
else
echo "Valid commands are start, stop, panel"
fi
